name: deploy main branch
on:
  push:
    branches:
      - main
      - testdeploy
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - run: yarn install
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}